### ISSUE TITLE
Update PydanticOutputParser class name  for topics_of_interest_parser

### ISSUE THREAD

**Issue by Akshaykumarcp** [emarco177/ice_breaker#10]
Reference file: output_parsers.py

My suggestion is to:
```diff
- topics_of_interest_parser = PydanticOutputParser(pydantic_object=IceBreaker)
+ topics_of_interest_parser = PydanticOutputParser(pydantic_object=TopicOfInterest)
```
Please refer below image:
![ice_breaker_outputparser](https://github.com/emarco177/ice_breaker/assets/16430258/856adcc4-e9a4-42d4-86c7-735fb8f96619)

**Comment by emarco177** [comment]
updated entire code base, plz review :)
