### ISSUE TITLE
'1-start-here' branch shows no code

### ISSUE THREAD

**Issue by SamuelDevdas** [emarco177/ice_breaker#2]
![image](https://github.com/emarco177/ice_breaker/assets/84823680/e448f195-ca52-487f-afc6-d411b026c2d2)

**Comment by emarco177** [comment]
Hi :)

The **ice_breaker.py** is not suppose to be in this begining branch
the only files that should be:
<img width="1893" alt="image" src="https://github.com/emarco177/ice_breaker/assets/44670213/a12e5988-c75c-4774-be6f-1e41d0c40d75">



cheeers
